### PR TITLE
lcdydxv4validator gentx

### PR DESCRIPTION
**Pull request by chiwalfrm**

### CODE REVIEW

**Comment by 2dpetkov** [comment]
Hi, @chiwalfrm,
Can you merge latest main into your branch, please?

**Comment by 2dpetkov** [comment]
@chiwalfrm I see no new commits in the PR, can you try pushing the changes to the [lcdydxv4validator/gentx](https://github.com/chiwalfrm/v4-testnets/tree/lcdydxv4validator/gentx) branch on [chiwalfrm/v4-testnets](https://github.com/chiwalfrm/v4-testnets)?

**Review by 2dpetkov — CHANGES_REQUESTED** [review]
I see no new commits in the PR, can you try pushing the changes to the [lcdydxv4validator/gentx](https://github.com/chiwalfrm/v4-testnets/tree/lcdydxv4validator/gentx) branch on [chiwalfrm/v4-testnets](https://github.com/chiwalfrm/v4-testnets)?

**Comment by chiwalfrm** [comment]
Done, I was in the wrong branch earlier, thanks for showing the way!

**Review by 2dpetkov — APPROVED** [review]

**Pull request merged**
