### PR TITLE
Figment Testnet 4 gentx

### PR DESCRIPTION
**Pull request by mnguyen-io**

### CODE REVIEW

**Comment by 2dpetkov** [comment]
@mnguyen-io, can you please merge latest main into your branch, so we can try running checks again?

**Review by 2dpetkov — CHANGES_REQUESTED** [review]
can you please merge latest main into your branch, so we can try running checks again?

**Comment by 2dpetkov** [comment]
@mnguyen-io kind reminder

**Comment by mnguyen-io** [comment]
> @mnguyen-io kind reminder

Done @2dpetkov

**Comment by mnguyen-io** [comment]
> > @mnguyen-io kind reminder
> 
> Done @2dpetkov

Sorry - let me just close this out and open a new one PR

**Pull request closed without merging**
