### PR TITLE
Added Node Guardians gentx

### PR DESCRIPTION
**Pull request by chichi13**

### CODE REVIEW

**Comment by 2dpetkov** [comment]
@chichi13, can you please merge latest main into your branch, so we can try running checks again?

**Review by 2dpetkov — CHANGES_REQUESTED** [review]
can you please merge latest main into your branch, so we can try running checks again?

**Comment by chichi13** [comment]
Done

**Comment by chichi13** [comment]
Okay, I think I did the PR before the update of the documentation. I'll push another genesis file.

**Pull request merged**
